### PR TITLE
Updated the MkDocs config from the deprecated format

### PR DESCRIPTION
**Pull request by d0ugal**

### CODE REVIEW

**Comment by tmcgee** [comment]
Is this format supported by readthedocs?

**Comment by d0ugal** [comment]
Yes, it has supported it for [almost a month](https://github.com/rtfd/readthedocs.org/commit/45ad95e8a181775247d65540eed625e4fa454e01#diff-5b28a0936ff1b3e6ec6fadb83bf59fb5) and it will take care of the first [build warning](https://readthedocs.org/builds/cmv/2996694/) you receive.

**Comment by DavidSpriggs** [comment]
Nice, thanks for the update!

**Comment by tmcgee** [comment]
@d0ugal, thanks!

**Pull request merged**
