### PR TITLE
Added link to more descriptive documentation.

### PR DESCRIPTION
**Pull request by mgd722**
http://docs.cmv.io/en/1.3.3/widgets/Identify/ has much more detailed information and already covers the topic of how to author the config object.

### CODE REVIEW

**Comment by DavidSpriggs** [comment]
@mgd722 Thanks for the fix and PR! Can I have you submit this against the development branch please. We do not accept PR's against master, only develop: https://github.com/cmv/cmv-app/tree/develop

**Comment by DavidSpriggs** [comment]
My bad, I was looking at the wrong repo, lol... merged and thanks!

**Comment by tmcgee** [comment]
@DavidSpriggs We don't want a hard-coded link to the documentation with a version number in it.  Should be a relative link,  yes?

**Comment by tmcgee** [comment]
@DavidSpriggs I just looked at the [latest docs build](http://docs.cmv.io/en/latest/configure/identify/)  and noticed that it does not create a valid hyperlink.  Need to use markdown and link to a relative page.

**Comment by DavidSpriggs** [comment]
Good point. Who wants to fix, @mgd722?

**Comment by mgd722** [comment]
Good catch, @tmcgee -- I'm definitely still getting the hang of this stuff.  Looking at it again, though, everything on the widgets/Identify/ page really only details how to make a config file.  Should that instead be moved to configure/identify/ and the widgets/Identify/ page be left blank?

**Comment by tmcgee** [comment]
I believe that this merge is causing the docs build process to fail. https://readthedocs.org/builds/cmv/

**Pull request merged**
