### PR TITLE
Add docs for the iconNode and menuItem that are passed when a dynamic…

### PR DESCRIPTION
**Pull request by green3g**
… sublayer's menu item is clicked

### CODE REVIEW

**Comment by tmcgee** [comment]
Thanks!

**Comment by tmcgee** [comment]
I am going to merge this and then add minimal documentation for the new 'subLayerMenu` added in [this PR in cmv-app](https://github.com/cmv/cmv-app/pull/401) as I don't think we've captured that.

**Comment by tmcgee** [comment]
never mind. it is already there. I just missed it.

**Comment by green3g** [comment]
Yup. I was just going to tell you I had thought I had the basics in there from awhile back.

**Pull request merged**
